import 'dart:typed_data';

import 'package:fitgo/models/passi.dart';
import 'package:floor/floor.dart';
import 'package:fitgo/database/entities/profile.dart';

@Entity(
  tableName: 'DatiDB')
  // foreignKeys: [
  //   ForeignKey(
  //     childColumns: ['profile_name'],
  //     parentColumns: ['username'],
  //     entity: Profile, ),],)

class DatiDB {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()
  final int ind;


  final String? profileName; 

  //For the sake of simplicity, a Todo has only a name.
  final double passi_today;
  final int profile_id;
  final int passi_week;
  final int date_steps;
  // @ColumnInfo(name: 'profile_name')
  // final String profileName;
  //Default constructor
  DatiDB(this.ind, this.profile_id, this.passi_today, this.passi_week, this.date_steps, this.profileName);

  dynamic retPassiToday(){
    return passi_today;
  }


  dynamic retDate(){
    return date_steps;
  }
  // Uint8List appendNewSteps(newSteps){
  //   passi_week.add(newSteps);
  //   return passi_week;
  // }
  
}