import 'package:floor/floor.dart';
import 'package:fitgo/database/entities/profile.dart';

@Entity(
  tableName: 'DatiDB')
  // foreignKeys: [
  //   ForeignKey(
  //     childColumns: ['profile_name'],
  //     parentColumns: ['username'],
  //     entity: Profile, ),],)

class DatiDB {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()
  final String? profileName; 

  //For the sake of simplicity, a Todo has only a name.
  final double passi_today;
  final int profile_id;
  // @ColumnInfo(name: 'profile_name')
  // final String profileName;
  //Default constructor
  DatiDB(this.profile_id, this.passi_today, this.profileName);

  dynamic retPassiToday(){
    return passi_today;
  }
  
}